 /// <reference types="cypress" /> 

 describe('Ultimateqa', ()=>{

  Cypress.on('uncaught:exception',(err,runnable) =>{
   return false
  })

  before(() => {

      cy.log('***** Test case started') 

  })

  beforeEach(() => {

    cy.visit('https://courses.ultimateqa.com/collections')
      
    
     }) 

      it('Page-1',()=>{

        cy.get('.logo').click()
        cy.get('.header__nav-item > a').click()
        cy.go('back')
        cy.get('.collections__heading').contains('Products').should('be.visible')
        cy.get('.form__control').click().should('be.visible')
        cy.get('#category-name').click().should('be.visible')

        cy.get('.products__list > :nth-child(1)').contains('Coding').should('be.visible')
        cy.get('.products__list > :nth-child(2)').contains('Complete').should('be.visible')
        cy.get('.products__list > :nth-child(3)').contains('Modern').should('be.visible')
        cy.get('.products__list > :nth-child(4)').contains('Java').should('be.visible')
        cy.get('.products__list > :nth-child(5)').contains('Selenium').should('be.visible')
        cy.get('.products__list > :nth-child(6)').contains('C#').should('be.visible')
        
        cy.get('.products__list > :nth-child(1)').click()
        cy.get('[data-qa="enroll-free__btn"]').click()
        cy.go(-1)
        cy.get('.course-curriculum__chapter-header > .toga-icon').click()
        cy.get('.footer__copyright').scrollIntoView({duration:2000})
        cy.go(-1)

        cy.get('.products__list > :nth-child(2)').click()
        cy.get('.et_pb_blurb_95 > .et_pb_blurb_content > .et_pb_blurb_container > .et_pb_module_header')
        .contains('So').should('be.visible').scrollIntoView({duration:2000})
        cy.get('#testButton')
        cy.get('.et_pb_accordion_item_1').click()
        const pop_url = "https://ultimateqa.com/testimonials/"
        cy.window().then(win => {
        win.location.href = pop_url
        cy.wait(2000)
        })
        cy.go(-2)

        cy.get('.products__list > :nth-child(3)').click()
        cy.get('[style="box-sizing: border-box; height: 100%; margin-left: 0.742969px; padding: 7.42969px 0px 6.68672px; position: relative; width: 100%;"]').click()
        cy.get(':nth-child(1) > .course-curriculum__chapter-content-wrapper > .course-curriculum__chapter-header > .toga-icon')
        .click()
        cy.wait(500)
        cy.get(':nth-child(2) > .course-curriculum__chapter-content-wrapper > .course-curriculum__chapter-header > .toga-icon')
        .click()
        cy.wait(500)
        cy.get(':nth-child(3) > .course-curriculum__chapter-content-wrapper > .course-curriculum__chapter-header > .toga-icon')
        .click()
        cy.wait(500)
        cy.get(':nth-child(4) > .course-curriculum__chapter-content-wrapper > .course-curriculum__chapter-header > .toga-icon')
        .click()
        cy.wait(500)
        cy.get(':nth-child(5) > .course-curriculum__chapter-content-wrapper > .course-curriculum__chapter-header > .toga-icon')
        .click()
        cy.wait(500)
        cy.get(':nth-child(6) > .course-curriculum__chapter-content-wrapper > .course-curriculum__chapter-header > .toga-icon')
        .click()
        cy.get('.footer__copyright').scrollIntoView({duration:2000})
        cy.go(-1)

        cy.get('.products__list > :nth-child(4)').click()
        cy.get('.footer__copyright').scrollIntoView({duration:500})
        cy.get('[data-qa="enroll-free__btn"]').click()
        cy.wait(500)
        cy.go(-1)
        cy.get('[style="box-sizing: border-box; height: 100%; margin-left: 0.742969px; padding: 7.42969px 0px 6.68672px; position: relative; width: 100%;"]').click()
        cy.get('.course-curriculum__chapter-header > .toga-icon').click()
        cy.go(-1)

        cy.get('.products__list > :nth-child(5)').click()
        cy.get(':nth-child(1) > .course-curriculum__chapter-content-wrapper > .course-curriculum__chapter-header > .toga-icon')
        .click()
        cy.wait(500)
        cy.get(':nth-child(2) > .course-curriculum__chapter-content-wrapper > .course-curriculum__chapter-header > .toga-icon')
        .click()
        cy.wait(500)
        cy.get(':nth-child(3) > .course-curriculum__chapter-content-wrapper > .course-curriculum__chapter-header > .toga-icon')
        .click()
        cy.wait(500)
        cy.get(':nth-child(4) > .course-curriculum__chapter-content-wrapper > .course-curriculum__chapter-header > .toga-icon')
        .click()
        cy.wait(500)
        cy.get(':nth-child(5) > .course-curriculum__chapter-content-wrapper > .course-curriculum__chapter-header > .toga-icon')
        .click()
        cy.wait(500)
        cy.get(':nth-child(6) > .course-curriculum__chapter-content-wrapper > .course-curriculum__chapter-header > .toga-icon')
        .click()
        cy.wait(500)
        cy.get('.button--link').click()
        cy.get('.footer__copyright').scrollIntoView({duration:2000})
        cy.go(-1)

        cy.get('.products__list > :nth-child(6)').click()
        cy.get('.footer__copyright').scrollIntoView({duration:2000})
        cy.get(':nth-child(1) > .course-curriculum__chapter-content-wrapper > .course-curriculum__chapter-header > .toga-icon')
        .click()
        cy.wait(500)
        cy.get(':nth-child(2) > .course-curriculum__chapter-content-wrapper > .course-curriculum__chapter-header > .toga-icon')
        .click()
        cy.wait(500)
        cy.get(':nth-child(3) > .course-curriculum__chapter-content-wrapper > .course-curriculum__chapter-header > .toga-icon')
        .click()
        cy.wait(500)
        cy.get(':nth-child(4) > .course-curriculum__chapter-content-wrapper > .course-curriculum__chapter-header > .toga-icon')
        .click()
        cy.wait(500)
        cy.get(':nth-child(5) > .course-curriculum__chapter-content-wrapper > .course-curriculum__chapter-header > .toga-icon')
        .click()
        cy.wait(500)
        cy.get(':nth-child(6) > .course-curriculum__chapter-content-wrapper > .course-curriculum__chapter-header > .toga-icon')
        .click()
        cy.wait(500)
        cy.get('.button--link').click()
        cy.go(-1)

        cy.get('.pagination__pages > :nth-child(1) > .fa').should('be.visible')
        cy.get('.pagination__pages > .active').should('be.visible')
        cy.get('.pagination__pages > :nth-child(3)').should('be.visible')
        cy.get(':nth-child(4) > .pagination__page-number').should('be.visible')
        cy.get('.pagination__pages > :nth-child(5) > a').should('be.visible')

        // //clickable
        cy.get('.pagination__pages > :nth-child(5) > a').should('be.visible').click()
        cy.get('.pagination__pages > :nth-child(1)').should('be.visible').click()

      })

      it(' Search bar & Sign in',()=>{

        cy.get('.form__control').type('Selenium').type('{enter}')
        cy.get('.form__control').clear()
        cy.get('.form__control').type('Java').type('{enter}')
        cy.get('.form__control').clear()
        cy.get('.form__control').type('Node').type('{enter}')

        cy.get('.header__nav-item > a').click()
        cy.get('input[type=email]').type('kaviyasiva0610@gmail.com')
        cy.get('input[type=password]').type('xxxxxx')
        cy.get('.form__button-group > .button').click()


      })

      it('Page-2',()=>{

        cy.get('.pagination__pages > :nth-child(3)').click()
        cy.get('.products__list > :nth-child(1)').contains('What').should('be.visible')
        cy.get('.products__list > :nth-child(2)').contains('Complete').should('be.visible')
        cy.get('.products__list > :nth-child(3)').contains('Selenium').should('be.visible')
        cy.get('.products__list > :nth-child(4)').contains('Sauce').should('be.visible')
        cy.get('.products__list > :nth-child(5)').contains('Page Objects').should('be.visible')
        cy.get('.products__list > :nth-child(6)').contains('Elements').should('be.visible')

        cy.get('.products__list > :nth-child(1)').click()
        cy.get('.course-curriculum__chapter-header > .toga-icon').click()
        cy.get('.footer__copyright').scrollIntoView({duration:500})
        cy.go(-1)

        cy.get('.products__list > :nth-child(2)').click()
        cy.get('.footer__copyright').scrollIntoView({duration:2000})
        cy.get('.text-icon__list > :nth-child(1)').should('be.visible')
        cy.get('.text-icon__list > :nth-child(2)').should('be.visible')
        cy.get('.text-icon__list > :nth-child(3)').should('be.visible')
        cy.get(':nth-child(1) > .course-curriculum__chapter-content-wrapper > .course-curriculum__chapter-header > .toga-icon')
        .click()
        cy.wait(500)
        cy.get(':nth-child(2) > .course-curriculum__chapter-content-wrapper > .course-curriculum__chapter-header > .toga-icon')
        .click()
        cy.wait(500)
        cy.get(':nth-child(3) > .course-curriculum__chapter-content-wrapper > .course-curriculum__chapter-header > .toga-icon')
        .click()
        cy.wait(500)
        cy.get(':nth-child(4) > .course-curriculum__chapter-content-wrapper > .course-curriculum__chapter-header > .toga-icon')
        .click()
        cy.wait(500)
        cy.go(-1)

        cy.get('.products__list > :nth-child(3)').click()
        cy.get('.footer__copyright').scrollIntoView({duration:2000})
        cy.get('.text-icon__list > :nth-child(1)').should('be.visible')
        cy.get('.text-icon__list > :nth-child(2)').should('be.visible')
        cy.get('.text-icon__list > :nth-child(3)').should('be.visible')
        cy.get(':nth-child(1) > .course-curriculum__chapter-content-wrapper > .course-curriculum__chapter-header > .toga-icon')
        .click()
        cy.wait(500)
        cy.get(':nth-child(2) > .course-curriculum__chapter-content-wrapper > .course-curriculum__chapter-header > .toga-icon')
        .click()
        cy.wait(500)
        cy.get(':nth-child(3) > .course-curriculum__chapter-content-wrapper > .course-curriculum__chapter-header > .toga-icon')
        .click()
        cy.wait(500)
        cy.get(':nth-child(4) > .course-curriculum__chapter-content-wrapper > .course-curriculum__chapter-header > .toga-icon')
        .click()
        cy.wait(500)
        cy.go(-1)

        cy.get('.products__list > :nth-child(4)').click()
        cy.get('.footer__copyright').scrollIntoView({duration:2000})
        cy.get('.text-icon__list > :nth-child(1)').should('be.visible')
        cy.get('.text-icon__list > :nth-child(2)').should('be.visible')
        cy.get('.text-icon__list > :nth-child(3)').should('be.visible')
        cy.get(':nth-child(1) > .course-curriculum__chapter-content-wrapper > .course-curriculum__chapter-header > .toga-icon')
        .click()
        cy.wait(500)
        cy.get(':nth-child(2) > .course-curriculum__chapter-content-wrapper > .course-curriculum__chapter-header > .toga-icon')
        .click()
        cy.wait(500)
        cy.get(':nth-child(3) > .course-curriculum__chapter-content-wrapper > .course-curriculum__chapter-header > .toga-icon')
        .click()
        cy.wait(500)
        cy.get(':nth-child(4) > .course-curriculum__chapter-content-wrapper > .course-curriculum__chapter-header > .toga-icon')
        .click()
        cy.wait(500)
        cy.go(-1)

        cy.get('.products__list > :nth-child(5)').click()
        cy.get('.footer__copyright').scrollIntoView({duration:2000})
        cy.get('.text-icon__list > :nth-child(1)').should('be.visible')
        cy.get('.text-icon__list > :nth-child(2)').should('be.visible')
        cy.get('.text-icon__list > :nth-child(3)').should('be.visible')
        cy.get(':nth-child(1) > .course-curriculum__chapter-content-wrapper > .course-curriculum__chapter-header > .toga-icon')
        .click()
        cy.wait(500)
        cy.get(':nth-child(2) > .course-curriculum__chapter-content-wrapper > .course-curriculum__chapter-header > .toga-icon')
        .click()
        cy.wait(500)
        cy.get(':nth-child(3) > .course-curriculum__chapter-content-wrapper > .course-curriculum__chapter-header > .toga-icon')
        .click()
        cy.wait(500)
        cy.get(':nth-child(4) > .course-curriculum__chapter-content-wrapper > .course-curriculum__chapter-header > .toga-icon')
        .click()
        cy.wait(500)
        cy.get(':nth-child(5) > .course-curriculum__chapter-content-wrapper > .course-curriculum__chapter-header > .toga-icon')
        .click()
        cy.wait(500)
        cy.get(':nth-child(6) > .course-curriculum__chapter-content-wrapper > .course-curriculum__chapter-header > .toga-icon')
        .click()
        cy.wait(500)
        cy.go(-1)

        cy.get('.products__list > :nth-child(6)').click()
        cy.get('.footer__copyright').scrollIntoView({duration:2000})
        cy.get('.text-icon__list > :nth-child(1)').should('be.visible')
        cy.get('.text-icon__list > :nth-child(2)').should('be.visible')
        cy.get('.text-icon__list > :nth-child(3)').should('be.visible')
        cy.get(':nth-child(1) > .course-curriculum__chapter-content-wrapper > .course-curriculum__chapter-header > .toga-icon')
        .click()
        cy.wait(500)
        cy.get(':nth-child(2) > .course-curriculum__chapter-content-wrapper > .course-curriculum__chapter-header > .toga-icon')
        .click()
        cy.wait(500)
        cy.get(':nth-child(3) > .course-curriculum__chapter-content-wrapper > .course-curriculum__chapter-header > .toga-icon')
        .click()
        cy.wait(500)
        cy.get(':nth-child(4) > .course-curriculum__chapter-content-wrapper > .course-curriculum__chapter-header > .toga-icon')
        .click()
        cy.wait(500)
        cy.get(':nth-child(5) > .course-curriculum__chapter-content-wrapper > .course-curriculum__chapter-header > .toga-icon')
        .click()
        cy.wait(500)
        cy.get(':nth-child(6) > .course-curriculum__chapter-content-wrapper > .course-curriculum__chapter-header > .toga-icon')
        .click()
        cy.wait(500)
        cy.get('.button--link').click()
        cy.go(-1)

  })

      it('Page-3',()=>{

        cy.get(':nth-child(4) > .pagination__page-number').click()

        cy.get('.products__list > :nth-child(1)').contains('execution').should('be.visible')
        cy.get('.products__list > :nth-child(2)').contains('Complete').should('be.visible')

        cy.get('.products__list > :nth-child(1)').click()
        cy.get('.footer__copyright').scrollIntoView({duration:2000})
        cy.get('.text-icon__list > :nth-child(1)').should('be.visible')
        cy.get('.text-icon__list > :nth-child(2)').should('be.visible')
        cy.get('.text-icon__list > :nth-child(3)').should('be.visible')
        cy.get(':nth-child(1) > .course-curriculum__chapter-content-wrapper > .course-curriculum__chapter-header > .toga-icon')
        .click()
        cy.wait(500)
        cy.get(':nth-child(2) > .course-curriculum__chapter-content-wrapper > .course-curriculum__chapter-header > .toga-icon')
        .click()
        cy.wait(500)
        cy.get(':nth-child(3) > .course-curriculum__chapter-content-wrapper > .course-curriculum__chapter-header > .toga-icon')
        .click()
        cy.wait(500)
        cy.get(':nth-child(4) > .course-curriculum__chapter-content-wrapper > .course-curriculum__chapter-header > .toga-icon')
        .click()
        cy.wait(500)
        cy.get(':nth-child(5) > .course-curriculum__chapter-content-wrapper > .course-curriculum__chapter-header > .toga-icon')
        .click()
        cy.go(-1)

        cy.get('.products__list > :nth-child(2)').click()
        cy.get('.footer__copyright').scrollIntoView({duration:2000})
        cy.get('.checklist___52981 > .checklist__container > .checklist__wrapper > .section__headings > .section__heading').should('be.visible')
        cy.get('.testimonials__list > :nth-child(1)').should('be.visible')
        cy.get('.testimonials__list > :nth-child(2)').should('be.visible')
        cy.get('.testimonials__list > :nth-child(3)').should('be.visible')
        cy.go(-2)

        

      })

      


})